// Generated by CoffeeScript 1.10.0
var counter, makeCounter;

makeCounter = function() {
  var count;
  count = 0;
  return {
    increment: function() {
      return count++;
    },
    getCount: function() {
      return count;
    }
  };
};

counter = makeCounter();

$('#bTest1').on("click", function() {
  counter.increment();
  return alert(counter.getCount());
});

//# sourceMappingURL=closures.js.map
